// MSU Error Codes mapping
export const MSU_ERROR_CODES = {
    "ERR10010": "İstekte zorunlu parametrelerden biri bulunamadı",
    "ERR10011": "Aynı parametre bir defadan fazla olarak gönderilmiş",
    "ERR10012": "Maksimum büyüklük değeri aşıldı",
    "ERR10013": "Geçersiz veri tipi",
    "ERR10014": "Geçersiz güvenlik algoritması",
    "ERR10015": "Geçersiz üye iş yeri bilgisi",
    "ERR10016": "Geçersiz tutar bilgisi",
    "ERR10017": "Geçersiz para birimi",
    "ERR10018": "Geçersiz dil seçimi",
    "ERR10019": "Genel hata",
    "ERR10020": "Geçersiz kullanıcı bilgileri",
    "ERR10021": "Boş parametre belirtilmiş, tüm parametreleri kontrol edin",
    "ERR10022": "Sipariş edilen ürünlerin toplam tutarı gerçek tutarla örtüşmüyor",
    "ERR10023": "Ödeme tutarı hesaplanan tutarla örtüşmüyor",
    "ERR10024": "Geçersiz vergi tutarı belirtilmiş",
    "ERR10025": "Belirtilen durumda vergi tutarı sıfır olmalıdır",
    "ERR10026": "Geçersiz entegrasyon modeli belirtilmiş",
    "ERR10027": "Geçersiz kart bilgisi (TOKEN) belirtilmiş",
    "ERR10028": "Belirtilen ödeme sistemi (sanal POS) bulunamadı",
    "ERR10029": "Belirtilen ödeme tipi (kampanya) bulunamadı",
    "ERR10030": "Belirtilen işlem bulunamadı",
    "ERR10031": "Bu işlem iade edilemez",
    "ERR10032": "Geçersiz iade tutarı belirtilmiş ya da bu işlem daha önce iade edilmiş",
    "ERR10033": "Bu işlem iptal edilemez",
    "ERR10034": "Belirtilen ödeme bulunamadı",
    "ERR10035": "Bu işlem için ön otorizasyon kaydı bulunmamaktadır",
    "ERR10036": "Tutar, orijinal istek tutarından daha büyük olamaz.",
    "ERR10037": "Belirtilen Kart Sahibi (Müşteri) kayıtlı değil",
    "ERR10038": "İlgili ödeme onay beklemektedir",
    "ERR10039": "Geçersiz ödeme durumu belirtilmiş",
    "ERR10040": "Geçersiz alt işlem (SUBACTION) belirtilmiş",
    "ERR10041": "Belirtilen kart daha önce eklenmiş",
    "ERR10042": "Kart daha önceden silinmiş",
    "ERR10043": "Geçersiz zaman aralığı belirtilmiş",
    "ERR10044": "Geçersiz tarih formatı belirtilmiş",
    "ERR10045": "Belirtilen kart numarası geçersizdir",
    "ERR10046": "Belirtilen kredi kartı geçerlilik tarihi geçersizdir",
    "ERR10047": "Kullanıcının API servislerini kullanma yetkisi bulunmamaktadır",
    "ERR10048": "Başarılı Bir İşlem zaten bu üye iş yeri sipariş numarası ile var",
    "ERR10049": "Ödeme, bu ödeme sistemi ile yapılamamaktadır.",
    "ERR10050": "Geçersiz HASH değeri",
    "ERR10051": "Herhangi bir ödeme sistemi (sanal pos) tanımı yok. Lütfen, kontrol ediniz.",
    "ERR10052": "Desteklenmeyen para birimi:",
    "ERR10053": "Kullanıcının bu üye iş yeri üzerinde işlem yapma yetkisi yok",
    "ERR10054": "Ödeme geçerlilik süresi maksimum limitin üstündedir.",
    "ERR10055": "Ödeme geçerlilik süresi minimum limitin altındadır.",
    "ERR10056": "Geçersiz API isteği belirtilmiş",
    "ERR10057": "Bayi Tipi sadece bir Ödeme Sistemi (Sanal POS) tipi ile ilişkilendirilebilir.",
    "ERR10058": "CARDTOKEN ve CURRENTCUSTOMERID parametreleri bir arada gönderilemez.",
    "ERR10059": "Bu müşteri no ile kayıtlı bir müşteri mevcuttur.",
    "ERR10060": "Geçersiz IP Adresi",
    "ERR10062": "Ondalık sayı parametresi sıfırdan küçük olamaz.",
    "ERR10063": "Üye işyeri ödeme sayfası ayarları zaten mevcut.",
    "ERR10064": "Üye işyeri ödeme sayfası ayarları bulunamadı.",
    "ERR10065": "Inconsistent installment information (KobiKart)",
    "ERR10066": "Belirtilen zaman bilgisi geçersiz ya da tutarsızdır",
    "ERR10067": "Invalid or Missing EXTRA parameter value",
    "ERR10068": "Geçersiz tekrar düzeni parametresi",
    "ERR10069": "Eşleniksiz iade sadece Finans ve İş Bankası ödeme sistemleri için desteklenmektedir.",
    "ERR10070": "Başlangı tarihi gelecekteki bir tarih olmalıdır",
    "ERR10071": "Geçersiz tekrarlı ödeme durum parametresi belirtilmiş",
    "ERR10072": "Harici iade, seçilen ödeme sistemi tarafından desteklenmemektedir",
    "ERR10073": "SaveCard ve ForceSave özellikleri birarada kullanılamaz.",
    "ERR10074": "Bu müşteri no ile kayıtlı bir müşteri mevcuttur.",
    "ERR10075": "Üye iş yeri görsel (logo) bilgisi hatalı",
    "ERR10076": "Geçersiz tekrarlı ödeme durum parametresi",
    "ERR10077": "Geçersiz şablon",
    "ERR10078": "İşlem kilitlidir",
    "ERR10079": "Bu kart markasını destekleyen bir ödeme sistemi bulunmamaktadır. Lütfen başka kart markası ile tekrar deneyin.",
    "ERR10080": "Lütfen, Üye İş Yeri Sipariş numarasını veya Ödeme Oturumu(Token) veriniz",
    "ERR10081": "Geçersiz işlem durumu",
    "ERR10082": "API kullanıcısının bu işlem için yetkisi yoktur.",
    "ERR10083": "Geçersiz Statü",
    "ERR10084": "Faiz veya indirim oranı sıfır değeri olmalıdır",
    "ERR10085": "Başlangıç tarihi, bitiş tarihten daha büyük olamaz.",
    "ERR10086": "Geçerli bitiş tarihi şimdiki tarihten daha büyük olmalıdır",
    "ERR10087": "Taksit sayı numarası zaten bu ödeme sistemi ile bir ödeme tipi var",
    "ERR10088": "Geçersiz taksit sayısı",
    "ERR10089": "Geçersiz nonce",
    "ERR10090": "İşlem Başarısız",
    "ERR10091": "Ödeme sistemi devre dışı bırakıldığı için işlem gerçekleştiremiyor. Lütfen Üye İş Yeri Süper Yöneticisiyle iletişime geçiniz",
    "ERR10092": "Geçersiz Offset Değeri",
    "ERR10093": "Geçersiz Limit",
    "ERR10094": "Tanımlı bir kart bulunamadı.",
    "ERR10095": "Kayıtlı bulunan tekrarlayan ödeme planlarından dolayı kart silinemez.",
    "ERR10096": "Geçersiz oturum (session) bilgisi.",
    "ERR10097": "Sonlandırılmış oturum (session) bilgisi.",
    "ERR10098": "Bu oturum anahtarının yapılmak istenen işleme yetkisi yoktur.",
    "ERR10099": "Ödeme sisteminden alınan 3D cevabı değiştirilmiş veya yanlış 3D anahtarı",
    "ERR10100": "Bu ödeme için birden fazla başarılı işlem vardır, lütfen PGTRANID parametresini kullanınız.",
    "ERR10101": "Lütfen POST istegini method body içerisinde gönderiniz. Query String içerisinde gönderilen parametreler güvenli değildir.",
    "ERR10102": "Geçersiz BIN değeri",
    "ERR10103": "İşlem isteği Inact RT servisi tarafından raporlanan fraud olasılığı nedeniyle reddedilmiştir.",
    "ERR10104": "Geçersiz kart bilgisi",
    "ERR10106": "Bu işlem 3D doğrulama ile gerçekleştirilemiyor.",
    "ERR10107": "Kullanilan ödeme sistemi kampanya kodunu desteklememektedir.",
    "ERR10108": "Puan kullanimi ödeme sistemi tarafindan desteklenmemektedir",
    "ERR10109": "This merchantpaymentId is used before and its session expired please use different merchantPaymentId",
    "ERR10110": "İstek ile mevcut sipariş numarasına ait oturumun tutar,kur,oturum tipi, url değeri ya da yapılmak istenen işlem değerlerinden biri uyuşmamaktadır",
    "ERR10111": "Puan sorgusu bu ödeme sistemi tarafından desteklenmemektedir",
    "ERR10112": "Puan json formatı geçersiz",
    "ERR10113": "Tekrarlı ödeme bulunamadı",
    "ERR10114": "Tekrarlı ödeme plan statüsü COMPLETED değiştirilemez",
    "ERR10115": "Tekrar sayısı 1 ile 99 arasında olmalıdır",
    "ERR10116": "Tekrarlı ödeme plan kodu mevcuttur",
    "ERR10117": "Ön otorizasyon yapan cüzdan oturumları sipariş numarası barındırmamalıdır",
    "ERR10118": "Geçersiz ticari kod parametresi",
    "ERR10119": "Ödeme sistemi puan parametresi hatalı, işlemin gönderileceği ödeme sisteminde gönderilen puan parametresi tanımlı değildir.",
    "ERR10120": "Puan değeri boş olamaz",
    "ERR10121": "Parçalı puan kullanımı bu ödeme sistemi tarafından desteklenmemektedir",
    "ERR10122": "3D doğrulama için Yasaklı BIN bilgileri",
    "ERR10123": "Aranan BKM İşlemi bulunamadı",
    "ERR10124": "Belirtilen tokena ait işlem bulundu.",
    "ERR10125": "İstenen işlem güncellenemez.",
    "ERR10126": "Payment System Type or EFT code is required if bin is not given",
    "ERR10127": "Geçersiz extra parametre değeri belirtilmiş",
    "ERR10128": "Tekrarlayan ödeme planı bir veya daha fazla işlenmiş işlem vardır bundan dolayı silinemez.",
    "ERR10129": "Ödeme Sistemi Güncelleme Edilemedi",
    "ERR10130": "Ödeme sistemi için verilen isim kullanımdadır",
    "ERR10131": "Ödeme sistem tipi mevcuttur",
    "ERR10132": "Bağlantı Hatası / Hatalı Veriler",
    "ERR10133": "Bu öğe kullanım dışı bırakılmıştır. Kullanım dışı bırakılmış öğeler güncellenemez.",
    "ERR10134": "Ödeme sistemi kullanım dışı olduğundan varsayılan olarak kabul edilemez. Lütfen önce etkinleştiriniz.",
    "ERR10135": "Varsayılan olarak işaretlenmiş bir ödeme sistemini kullanım dışı bırakamazsınız. Lütfen önce başka bir ödeme sistemini varsayılan olarak işaretleyiniz.",
    "ERR10136": "Uyumsuz İstek Parametresi",
    "ERR10137": "ÖDENMİŞ veya İPTAL EDİLMİŞ ödeme.",
    "ERR10138": "Müşteri bulunamadı",
    "ERR10139": "Kimlik numarası 11 rakam içermelidir",
    "ERR10140": "Kampanya sorgusu kullanılan ödeme sistemi tarafından desteklenmemektedir.",
    "ERR10141": "Geçersiz Etiketler Formatı.",
    "ERR10142": "Tekrar tutarlarının toplamı, tekrarlı ödeme planı toplam tutarına eşit değil.",
    "ERR10143": "Tekrarlı ödeme - kart ilişkisi bulunamadı",
    "ERR10144": "Geçersiz kampanya formatı.",
    "ERR10145": "Tekrarlayan Ödeme Durumu sadece Manually Paid güncellenebilir",
    "ERR10146": "Tekrarlayan Ödeme Durumu güncellenemez",
    "ERR10147": "Tekrarlayan Ödeme bulunamadı",
    "ERR10148": "Tekrarlayan plan durumu yalnızca Aktif veya Inaktif (Pasif) olabilir",
    "ERR10149": "Tekrarlanan Planın kartları yoksa aktif edilemez",
    "ERR10150": "Tekrarlı Ödeme Planı ya da herhangi bir Tekrarlı Ödeme bilgisini güncelleyebilmek için öncelikle Tekrarlı Ödeme Plan durumunu güncellemeniz gerekmektedir",
    "ERR10151": "İstek işlem kurallarına uygun değil.",
    "ERR10152": "Uygulanacak kart tipi seçimi yapılmalıdır",
    "ERR10153": "Tekrar tutarı sıfırdan büyük olmalıdır",
    "ERR10154": "Bu işlem 3D doğrulama kullanılmadan yapılamaz",
    "ERR10155": "Merchant can be enabled or disabled just by system users.",
    "ERR10156": "Belirtilen Ödeme Kuralı bulunamadı",
    "ERR10157": "Belirtilen bayi bulunamadı",
    "ERR10158": "Bu kod bilgisine sahip bir bayi hali hazırda bulunmaktadır.",
    "ERR10159": "Bayi deaktive durumdadir. Bu işlem yapılamaz.",
    "ERR10160": "üye iş yeri kullanıcısı bulunamadı.",
    "ERR10161": "Onay bekleyen bir işlem bulunmaktadır.",
    "ERR10162": "Sadece Satış Temsilcisi rolündeki kullanıcılar veya Bayi Süper kullanıcıları bayi ile ilişkilendirilebilir.",
    "ERR10163": "Geçersiz alt durum",
    "ERR10164": "Kullanıcının otomatik işlem yapma yetkisi yoktur.",
    "ERR10165": "Girdiğiniz bayi tipi adı önceden tanımlanmıştır.",
    "ERR10166": "Belirtilen bayi tipi bulunamadı",
    "ERR10167": "Bu bayi tipi tanımlı bir bayi tarafından kullanılmaktadır. Bayi ilişkisi kaldırılmadı sürece silinemez.",
    "ERR10168": "Bayi Ödeme Tipi belirtilen ödeme tipi ve bayi kodu ile bulunamamıştır.",
    "ERR10169": "Üye iş yeri e-posta adresi tanımlı.",
    "ERR10170": "Bayi ödeme tipi bu ödeme tipi ve bayi için tanımlıdır.",
    "ERR10171": "Bu ödeme sistemi belirtilen üye iş yeri için tanımlı değildir.",
    "ERR10172": "Üye iş yeri için belirtilen içerikte bir ödeme kuralı zaten mevcut.",
    "ERR10173": "Bu parametrenin değeri 0.00 ile 99.99 arasında bir değer olmalıdır.",
    "ERR10174": "Geçersiz işlem kuralları listesi",
    "ERR10175": "Bu ödeme için abonelikler boş olarak gönderilemez. Lütfen kontrol ediniz.",
    "ERR10176": "Üzgünüz, bu kullanıcıya ait rol bilgisini daha als seviye bir rol olarak değiştiremezsiniz!",
    "ERR10177": "Kullanıcı güncelleme edilemedi",
    "ERR10178": "Yeni şifreleriniz birbirini tutmaktadır. Lütfen yeni şifrenizi her iki alana da doğru olarak giriniz.",
    "ERR10179": "Mesaj içeriği bulunamadı",
    "ERR10180": "Şifreniz en az 1 büyük harf, 1 küçük harf, 1 sayı ve 1 sembol içermeli ve en az 12 karakter uzunluğunda olmalıdır.",
    "ERR10181": "Bu çağrı için PGTRANIDTOREFUND parametresi boş olamaz.",
    "ERR10182": "Bu tip ve dilde mesaj içeriği zaten mevcut.",
    "ERR10183": "Bu fatura bilgisi belirtilen bayi ve üye iş yeri için zaten var",
    "ERR10184": "Fatura bulunamadı",
    "ERR10185": "Bu fatura başarılı olarak ödenmiş ve silinemez ve güncellenemez.",
    "ERR10187": "Faturalar sadece bayiler için tanımlanabilir.",
    "ERR10188": "Faturaya dair ödenecek tutardır, Orijinal tutardan fazla olamaz.",
    "ERR10189": "Fatura ödeme tarihi, fatura düzenlenme tarihinden daha sonra olmalıdır.",
    "ERR10190": "Ödeme Sistemi Kuralı Zaten Mevcut",
    "ERR10191": "Kullanıcı bulunamadı",
    "ERR10192": "Kullanıcı hesabı aktif değil",
    "ERR10193": "Kullanıcı hesabı kilitli",
    "ERR10194": "Şifreyi yeniden oluşturmak için token bilgisi yok ya da süresi dolmuş",
    "ERR10195": "Geçersiz kullanıcı adı ve/veya şifre",
    "ERR10196": "IP adresi sistemde tanımlı izin verilen IP adresleri listesinde bulunamadı",
    "ERR10197": "Bu kart zaten başka bir müşteri için kaydedildi.",
    "ERR10198": "Bu kart tipi eklenemez. Lütfen başka bir kart ekleyiniz.",
    "ERR10199": "İşlem tipi bu ödeme sistemi tarafından desteklenmiyor.",
    "ERR10200": "Beklenemedik ödeme sistemi entegrasyonu hatası",
    "ERR10201": "İletilen bayi ve/veya alt bayi kodu uyumlu değildir, lütfen kontrol ediniz.",
    "ERR10202": "VKN 9 rakam içermelidir.",
    "ERR10203": "ENDATE, STARTDATE'e eşit veya büyük olmalıdır.",
    "ERR10204": "Bu değerler ile Bayi Komisyon Oranı zaten mevcut.",
    "ERR10205": "Bayi Komisyon Oranı bulunamadı.",
    "ERR10206": "Kurallar yalnızca SubDealers için eklenebilir, Ana Bayiyi kontrol edin",
    "ERR10207": "Kurallar kodu çözülemez(decoded), kodlanmış RULE parametresini kontrol edin",
    "ERR10208": "Ana Bayı Kuralları aşıldı",
    "ERR10209": "Ticari kod için maksimum taksit sayısı aşıldı.",
    "ERR10210": "Varsayılan Alt bayi tipi silinemez. Lütfen öncelikle yeni bir Alt bayi tipi tanımlayınız.",
    "ERR10211": "Parçalı Ödeme Kodu Mevcut",
    "ERR10212": "Geçersiz Şehir ID",
    "ERR10213": "Lütfen bir varsayılan ödeme sistemi (sanal pos) olduğundan emin olun.",
    "ERR10214": "Üye İş Yeri için Ödeme Sistemi (VPOS) tipi ve adı mevcut",
    "ERR10215": "DEALERTYPENAME çoklu ödeme sistemi eklendiğinde kullanılır",
    "ERR10216": "Bilinmeyen CVV extra parametresi, parametre YES veya NO olabilir",
    "ERR10217": "Parçalı iptal işlemi bu ödeme sistemi tarafından desteklememektedir.",
    "ERR10218": "Parçalı iptal bu işlem tipi için desteklenmemektedir.",
    "ERR10219": "Geçersiz iptal tutarı",
    "ERR10220": "There is a active BIN rule with the same name",
    "ERR10221": "BIN rule not found for the merchant",
    "ERR10222": "Bu alanlardan biri sağlanmalı (Kart Ağı, Kart Tipi, Kart Markası, Ülke, Kart Bankası)",
    "ERR10223": "Bir BIN Kurali ile farkli isim, ancak aynı parametrelere zaten tanımlanmış",
    "ERR10224": "Maksimum taksit sayısı aşıldı.",
    "ERR10225": "Country Code ve Foreign parametreleri aynı anda gönderilemez.",
    "ERR10226": "Özel alan grubu bulanamadı",
    "ERR10227": "Aynı isimle özel alan grubu zaten mevcut",
    "ERR10228": "Özel Alan Geçerlilikleri Alanı Geçersiz",
    "ERR10229": "Özel alan zaten mevcut",
    "ERR10230": "Özel alan bulunamadı",
    "ERR10231": "Geçersiz Özelleştirilen Alan",
    "ERR10232": "Özelleştirilen Alan Zorunlu",
    "ERR10233": "Bu işlemi gerçekleştirmek için özelleştirilen alan yönetimi özelliği gereklidir.",
    "ERR10234": "Geçersiz kart hesap kesim günü",
    "ERR10235": "E-posta zaten sistemde başka bir kullanıcı için kayıtlıdır.",
    "ERR10236": "Ödeme Sistemi Kuralı Bulunamadı",
    "ERR10237": "İlişkili Ödeme Sistemi bulunamadı",
    "ERR10238": "Bu işlem için Ödeme Sistemi Paylaşım Yönetimi özelliğine sahip olmak gerekmektedir.",
    "ERR10239": "Geçersiz ayarlar parametresi",
    "ERR10240": "Mutabakat şeması mevcut değil",
    "ERR10241": "Mutabakat şeması zaten var",
    "ERR10242": "Kullanıcı tanımlı ya da aktif değil. Lütfen kullanıcı bilgisini kontrol edin.",
    "ERR10243": "USER parametresi sizin üye iş yeriniz icin kullanilamaz.",
    "ERR10244": "Belirtilen tarih aralığını kapsayan bir şema bulunmaktadır. Lütfen başka bir aralık giriniz.",
    "ERR10245": "Kullanımda olan mutabakat şemasını düzenleyemezsiniz.",
    "ERR10246": "CARDPAN hatalı format.",
    "ERR10247": "NAMEONCARD, CARDEXPIRY ve CARDPANCVV parametrelerini CARDPANTYPE parametresi ile aynı anda kullanamazsınız.",
    "ERR10248": "CARDPANTYPE parametresi CARDTOKEN parametresi ile aynı anda kullanamazsınız.",
    "ERR10249": "SAVECARD parametresini CARDPANTYPE parametresi ile aynı anda kullanamazsınız.",
    "ERR10250": "CARDPANTYPE parametresini INSURANCE olarak kullanma yetkiniz yok.",
    "ERR10251": "CARDPANTYPE parametresiyle 3D Satışa izin verilmiyor.",
    "ERR10252": "Satıcı banka başına birden fazla hesabı desteklemez",
    "ERR10253": "Aktivasyon tarihi bugünün gece yarısından büyük ya da eşit olmalıdır.",
    "ERR10254": "Bitiş tarihi bugünün gece yarısından büyük ya da eşit olmalıdır.",
    "ERR10255": "Bitiş tarihi aktivasyon tarihinden büyük olmalıdır.",
    "ERR10256": "Ön otorizasyon bu kart pan tipi için ödeme sistemi tarafından desteklenmemektedir.",
    "ERR10257": "Identity ve HostSubMerchantId parametreleri aynı anda kullanılamaz.",
    "ERR10258": "Idendity alanı 10 veya 11 hane olmalıdır.",
    "ERR10259": "Geçersiz Merchant Payment ID",
    "ERR10260": "Üye İş Yeri bu özelliği desteklemiyor.",
    "ERR10261": "Faturalarda ön kimlik kullanımına izin verilmiyor",
    "ERR10262": "INVOICEID'nin ön kimlik doğrulamalı faturalarla kullanılmasına izin verilmiyor",
    "ERR10263": "Üye İş Yeri Harici Kimlik DoÄrulama seÃ§eneğini desteklemiyor.",
    "ERR10264": "Harici kullanıcı, API Kullanıcısı olarak kullanılamaz.",
    "ERR10265": "Harici kullanıcı zaten var.",
    "ERR10266": "Harici kullanıcı mevcut değil.",
    "ERR10267": "Bu API Eylemi, Harici Kimlik DoÄrulama seÃ§eneğiyle kullanılamaz.",
    "ERR10268": "Bu konum kimliğine sahip konum zaten mevcut",
    "ERR10269": "ERR10269",
    "ERR10270": "ERR10270",
    "ERR10271": "Bu konum kimliğine sahip konum bulunamadı",
    "ERR10272": "Bu konum kimliğine ve bayi koduna sahip Bayi Konumu zaten mevcut",
    "ERR10273": "Bu konum kimliğine ve bayi koduna sahip Bayi Konumu bulunamadı",
    "ERR10274": "Bayi iş kolu zaten var",
    "ERR10275": "Bayi iş kolu mevcut değil",
    "ERR10276": "Uyumsuz MAC.",
    "ERR10277": "Fatura silinemedi",
    "ERR10278": "İptal edilen fatura ödemede kullanılamaz",
    "ERR10279": "Ödeme sistemi grup data bilgilerini sahip olmadığı için MERCHANTGROUPID parametresini kullanamazsınız.",
    "ERR10280": "Ödeme planı sorgusu ödeme sistemi tarafindan desteklenmemektedir.",
    "ERR10281": "Tanım ve Kimlik Vergi Numarası ekstra parametreleri gereklidir",
    "ERR10282": "ERR10282",
    "ERR10283": "Ödeme tutarı, bu kullanıcı için izin verilen maksimum tutarı aşıyor",
    "ERR10284": "BIN bazlı kural sebebiyle ödemeye izin verilmedi",
    "ERR10285": "Kart kaydedilemedi.",
    "ERR10286": "Bu işlem için pgTranId parametresine izin verilmiyor. Lütfen bunun yerine MERCHANTPAYMENTID parametresini sağlayın.",
    "ERR10287": "İşleme izin verilmedi. Üye işyerinin seçilen ödeme sistemi için bir mütabakat şeması bulunmamaktadır.",
    "ERR10288": "Payment type maturity exist for this payment system with the additional maturity given",
    "ERR10289": "Additional maturity can not be bigger than maximum installment count",
    "ERR10290": "INVOICETYPE parametre değeri ile EXTRA'daki Preauth değeri uyuşmuyor",
    "ERR10291": "Tutar, acquire (kazanım) minimum tutardan düşük olmamalıdır.",
    "ERR10292": "JWT oluşturulamadı",
    "ERR10293": "Yabancı kart numarası ile işlem yapılamaz.",
    "ERR10294": "BIN kuralı tipi ile çoklu ödeme sistemi hesabı olan üye iş yeri için bir ödeme sistemi bulunamadı.",
    "ERR10295": "PAYMENTSYSTEMPOOL formatı hatalı. Lütfen doğru PAYMENTSYSTEMPOOL formatı gönderin.",
    "ERR10296": "Ödeme sistemi adı hatalı. Lütfen PAYMENTSYSTEMPOOL için doğru ödeme sistemi adı gönderin.",
    "ERR10297": "Ödeme sistemi aktif değil. Lütfen PAYMENTSYSTEMPOOL için aktif bir ödeme sistemi gönderin.",
    "ERR10298": "Birden fazla/az \"varsayılan\" ödeme sistemi gönderildi. Lütfen PAYMENTSYSTEMPOOL için bir tane \"default\" ödeme sistemi gönderin.",
    "ERR10299": "Aynı bankaya ait birden fazla ödeme sistemi gönderilemez. Lütfen PAYMENTSYSTEMPOOL için aynı bankaya ait bir tane ödeme sistemi gönderin.",
    "ERR10300": "Girmiş olduğunuz kart bilgilerine ait (Vakıf Bank Tarım Kart) herhangi bir ödeme sistemi bulunamamıştır. Lütfen üye işyeri ile iletişime geçiniz.",
    "ERR10301": "Devam Eden bir İşlem zaten bu üye iş yeri sipariş numarası ile var",
    "ERR10302": "Kart Bilgileri Dogrula desteklememektedir.",
    "ERR10303": "Fiziksel Pos İşlemleri için PAYMENTSYSTEMTYPE desteklenmez",
    "ERR10304": "Kanal kodu panelde tanımlı değil.",
    "ERR10305": "Geçersiz Rol",
    "ERR10306": "ERR10306",
    "ERR10307": "Ödemeyi bu kartla gerçkeleştiremezsiniz, lütfen başka bir kartla yeniden deneyiniz.",
    "ERR10308": "Bayi Kodu ve BNPL Ürün Kodu değerleri eşleşmemektedir.",
    "ERR10309": "Belirtilen ödeme yöntemiyle işlem yapma yetkiniz yok.",
    "ERR10310": "Veriler şifrelenemedi.",
    "ERR10311": "Komisyon şeması zaten var",
    "ERR10312": "Komisyon şeması mevcut değil.",
    "ERR10313": "Üye iş yeri özelliği bulunmamaktadır",
    "ERR10314": "Üye iş yeri istek hız limiti aşıldı. Lütfen daha sonra tekrar deneyin.",
    "ERR10315": "Session token ile yapılabilecek maksimum yeniden deneme sayısına ulaşıldı.",
    "ERR20001": "Manuel onay için bankanızla iletişime geçiniz",
    "ERR20002": "Sahte onay, bankanızla iletişime geçiniz",
    "ERR20003": "Geçersiz üye iş yeri ya da servis sağlayıcı",
    "ERR20004": "Karta el koyunuz",
    "ERR20005": "Kart sahibine bu işlem yetkisi verilmemiştir veya girilen kart bilgileri hatalı olabilir. Lütfen kart sahibi bankası ile iletişime geçiniz.",
    "ERR20006": "Hata (Sanal POS ya da banka tarafında sadece kayıt güncelleme cevapları bulundu)",
    "ERR20007": "Karta el koyunuz - Özel nedenler",
    "ERR20008": "Sahte onay, bankanızla iletişime geçiniz",
    "ERR20009": "Kart yenilenmiş. Yeni kart ile deneyiniz.",
    "ERR20010": "Kısmi Onay (Partial Approval) - Tekrar Deneyin",
    "ERR20011": "Sahte onay (VIP), bankanızla iletişime geçiniz",
    "ERR20012": "Sanal pos bankası tarafından desteklenmeyen işlem, yapılan işlem kriterlere uygun değildir.",
    "ERR20013": "Sanal POS hatası: Geçersiz tutar bilgisi",
    "ERR20014": "Geçersiz hesap ya da kart numarası belirtilmiş",
    "ERR20015": "Böyle bir banka (issuer) bulunamadı",
    "ERR20016": "Bakiye yetersiz. Yarın tekrar deneyin.",
    "ERR20017": "İşlem iptal edildi.",
    "ERR20018": "Kart kapalı. Bankayla iletişime geçin.",
    "ERR20019": "Sanal POS hatası: Tekrar deneyiniz",
    "ERR20020": "Sanal POS hatası: Geçersiz / Hatalı tutar",
    "ERR20021": "Banka / Sanal POS tarafında işlem yapılamıyor",
    "ERR20023": "Kart No bulunamadı.",
    "ERR20025": "Sanal POS hatası: Kayıt oluşturulamadı",
    "ERR20026": "Sanal POS tarafında işlem bulunamadı",
    "ERR20027": "Sanal POS hatası: Banka reddetti",
    "ERR20028": "Sanal POS hatası: Original is denied",
    "ERR20029": "Sanal POS hatası: Original not found",
    "ERR20030": "Sanal POS tarafında switch bazlı format hatası",
    "ERR20031": "Sanal POS hatası: Issuer sign-on olmamış.",
    "ERR20032": "Sanal POS tarafında genel yönlendirme hatası",
    "ERR20033": "Belirtilen kredi kartının geçerlilik süresi bitmiştir",
    "ERR20034": "İşlemde sahtecilik (fraud) şüphesi",
    "ERR20036": "Sanal POS hatası: Kısıtlanmış kart",
    "ERR20037": "Sanal POS hatası: Banka (Issuer) kartı geri çağrıyor",
    "ERR20038": "Sanal POS hatası: İzin verilen PIN deneme sayısı aşıldı",
    "ERR20039": "Sanal POS hatası: Kredi hesabı bulunamadı",
    "ERR20040": "Sanal POS hatası: İade işlemi gün sonundan önce yapılamaz",
    "ERR20041": "Sanal POS hatası: Kayıp kart, karta el koyunuz",
    "ERR20043": "Sanal POS hatası: Çalıntı kart, karta el koyunuz",
    "ERR20051": "Belirtilen kredi kartının limiti bu işlem için yeterli değildir",
    "ERR20052": "Sanal POS hatası: Çek hesabı bulunamadı",
    "ERR20053": "Sanal POS hatası: Tasarruf hesabı bulunamadı",
    "ERR20054": "Kartın kullanım süresi geçmiş",
    "ERR20055": "Sanal POS hatası: Hatalı / Geçersiz PIN değeri",
    "ERR20056": "Sanal POS hatası: Kart bilgisi bulunamadı",
    "ERR20057": "Kart sahibine bu işlem yetkisi verilmemiştir. Lütfen kart sahibi bankası ile iletişime geçiniz.",
    "ERR20058": "Yapılmak istenen işleme banka tarafından izin verilmemiştir. Lütfen üye işyeri ile iletişime geçiniz.",
    "ERR20059": "İşlemde sahtecilik (fraud) şüphesi vardır",
    "ERR20061": "Sanal POS hatası: Beklenen işlem tutar sınırı aşıldı",
    "ERR20062": "Belirtilen kredi kartı kısıtlanmıştır",
    "ERR20063": "Sanal POS tarafında güvenlik ihlali durumu",
    "ERR20065": "Sanal POS hatası: Beklenen işlem sınırı aşıldı",
    "ERR20068": "Time out. İşlemi iptal ediniz.",
    "ERR20069": "Kartınız internet alışverişine kapalıdır. Lütfen bankanız ile iletişime geçiniz",
    "ERR20073": "Genel limit asim.",
    "ERR20075": "Kart sahibine bu işlem yetkisi verilmemiştir. Lütfen kart sahibi bankası ile iletişime geçiniz. Kart şifre giriş limiti aşıldı.",
    "ERR20076": "Sanal POS anahtar eşzamanlama hatası",
    "ERR20077": "Sanal POS hatası: Geçersiz / Tutarsız bilgi gönderildi",
    "ERR20078": "Lütfen kart sahibi bankası ile iletişime geçiniz.",
    "ERR20079": "Sanal POS hatası: ARQC failed / ARQC başarısız",
    "ERR20080": "Geçersiz tarih bilgisi",
    "ERR20081": "Sanal POS şifreleme hatası",
    "ERR20082": "Geçersiz / Hatalı CVV değeri",
    "ERR20083": "PIN değeri doğrulanamıyor",
    "ERR20084": "Geçersiz / Hatalı CVV değeri",
    "ERR20085": "Sanal POS tarafında reddedildi (Genel)",
    "ERR20086": "Doğrulanamadı",
    "ERR20088": "Şifreleme hatası. Lütfen daha sonra tekrar deneyiniz.",
    "ERR20089": "Doğrulama hatası. Lütfen daha sonra tekrar deneyiniz.",
    "ERR20090": "Gün sonu yapılıyor. Lütfen daha sonra tekrar deneyiniz.",
    "ERR20091": "Banka / Sanal POS şu an işlem gerçekleştiremiyor",
    "ERR20092": "Zaman aşımı nedeniyle teknik iptal gerçekleşitiriliyor",
    "ERR20093": "Kartınız e-ticaret işlemlerine kapalıdır. Bankanızı arayınız.",
    "ERR20094": "Çoklu işlem",
    "ERR20095": "Günlük toplam hatalı. İptal reddedildi.",
    "ERR20096": "Sanal POS tarafında genel hata",
    "ERR20098": "Çoklu iptal (Duplicate reversal)",
    "ERR20099": "Lütfen yeniden deneyiniz, sorun devam ederse bankanızla iletişime geçiniz.",
    "ERR20127": "Sipariş numarası tekrar problemi. Lütfen başka bir kart kullanarak ödemenize devam ediniz. Sorun devam ederse lütfen ödeme yaptığınız kurum ya da ödeme servis sağlayıcısı ile iletişime geçiniz",
    "ERR200GK": "Sanal POS hatası: Bu terminalde yanabcı kartlar için yetki bulunmamaktadır.",
    "ERR200SF": "Detaylar için sanal POS cevabındaki HOSTMSG alanını kontrol ediniz.",
    "ERR200YK": "Kart kara listede bulunuyor",
    "ERR30001": "Bu işlem Threat Metrix (TMX) tarafından reddedilmiştir. İlgili detaylar için lütfen işlem loglarını ve TMX portal kayıtlarını inceleyiniz.",
    "ERR30002": "3D işlemi başarılı şekilde sonlanmadı.",
    "ERR30003": "Bu istek işlem kuralları tarafından reddedilmiştir.",
    "ERR30004": "Bu istek fraud (sahtecilik) kuralları tarafından reddedilmiştir.",
    "ERR30005": "Banka veya 3D secure sistemi tarafından yanıt alınamadı."
};